//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Trade Corridors Fund (NTCF).
        /// </summary>
        internal static string ApplicationMenuHeader {
            get {
                return ResourceManager.GetString("ApplicationMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to submit the following data?.
        /// </summary>
        internal static string AreYouSureYouWantToSubmit {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Resources.
        /// </summary>
        internal static string DefaultResources {
            get {
                return ResourceManager.GetString("DefaultResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string DEV {
            get {
                return ResourceManager.GetString("DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web server is incapable of performing the request. Please try your request again later. Please contact the Web server&apos;s administrator if this problem persists..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an expression of interest for the National Trade Corridors Fund - Continuous call.
        /// </summary>
        internal static string HomePageHeader {
            get {
                return ResourceManager.GetString("HomePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start a new expression of interest for the National Trade Corridors Fund - Continuous call or continue one that has not yet been submitted, click on &lt;strong&gt;New or Existing Expression of Interest&lt;/strong&gt; in the left-side navigation menu..
        /// </summary>
        internal static string HomePageNewOrExistingBody {
            get {
                return ResourceManager.GetString("HomePageNewOrExistingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start a new expression of interest or continue an existing one:.
        /// </summary>
        internal static string HomePageNewOrExistingHeader {
            get {
                return ResourceManager.GetString("HomePageNewOrExistingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only have one draft expression of interest at a time. After you submit the expression of interest, you can start a new one..
        /// </summary>
        internal static string HomePageOnlyOne {
            get {
                return ResourceManager.GetString("HomePageOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have already submitted an expression of interest for the National Trade Corridors Fund  - Continuous call and would like to see the information you submitted, please refer to the email you received after submitting to find a link to your expression of interest..
        /// </summary>
        internal static string HomePageSubmittedBody {
            get {
                return ResourceManager.GetString("HomePageSubmittedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view a submitted expression of interest:.
        /// </summary>
        internal static string HomePageSubmittedHeader {
            get {
                return ResourceManager.GetString("HomePageSubmittedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New or Existing Expression of Interest.
        /// </summary>
        internal static string NewOrExistingSubmission {
            get {
                return ResourceManager.GetString("NewOrExistingSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are applying for the Northern call, please follow &lt;a href=&quot;{0}&quot;&gt;this link&lt;/a&gt;..
        /// </summary>
        internal static string NorthernCall {
            get {
                return ResourceManager.GetString("NorthernCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find that Web page.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry you ended up here. Sometimes a page gets moved or deleted..
        /// </summary>
        internal static string PageNotFoundMessage {
            get {
                return ResourceManager.GetString("PageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the home page.
        /// </summary>
        internal static string ReturnHomePage {
            get {
                return ResourceManager.GetString("ReturnHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Received.
        /// </summary>
        internal static string SubmissionReceived {
            get {
                return ResourceManager.GetString("SubmissionReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your submission has been received. You will receive a confirmation email shortly..
        /// </summary>
        internal static string SubmissionReceivedMessage {
            get {
                return ResourceManager.GetString("SubmissionReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &lt;strong&gt;Submit Expression of Interest&lt;/strong&gt;, you acknowledge that the organization is responsible for all cost overruns and that the submitted information may be shared, or referred to, by other federal departments and agencies, including crown corporations..
        /// </summary>
        internal static string SubmitAcknowledgement {
            get {
                return ResourceManager.GetString("SubmitAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon submission, Transport Canada will send an email confirmation of your expression of interest submission to both contact individuals provided in Section 1B. Your email will contain a link to the expression of interest you have submitted.&lt;br&gt;&lt;br&gt;If these contacts do not receive an email confirmation, please email the NTCF generic inbox at &lt;a href=&quot;mailto:{0}&quot;&gt;{0}&lt;/a&gt;..
        /// </summary>
        internal static string SubmitEmailMessage {
            get {
                return ResourceManager.GetString("SubmitEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Expression of Interest.
        /// </summary>
        internal static string SubmitEOI {
            get {
                return ResourceManager.GetString("SubmitEOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill out contact information in order to submit the expression of interest..
        /// </summary>
        internal static string SubmitErrorMessage {
            get {
                return ResourceManager.GetString("SubmitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        internal static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
    }
}
