SET SERVEROUTPUT ON;

BEGIN
	dbms_output.enable(1000000);
	dbms_output.put_line('=======================================================');
	dbms_output.put_line('== Resetting All Sequences');

	dbms_output.put_line('=======================================================');
	dbms_output.put_line('== Lookup Tables');

	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'TY001_LANGUAGE', 'LANGUAGE_ID', 'TY001_LANGUAGE_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'TY003_RESOURCE', 'RESOURCE_ID', 'TY003_RESOURCE_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'TY007_FIELD_SET', 'FIELD_SET_ID', 'TY007_FIELD_SET_SEQ');
	
	dbms_output.put_line('=======================================================');
	dbms_output.put_line('== Data Tables');

	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY000_USER', 'USER_ID', 'YY000_USER_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY001_PROGRAM', 'PROGRAM_ID', 'YY001_PROGRAM_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY002_TIME_WINDOW', 'TIME_WINDOW_ID', 'YY002_TIME_WINDOW_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY003_FORM', 'FORM_ID', 'YY003_FORM_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY004_SECTION', 'SECTION_ID', 'YY004_SECTION_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY005_FIELD', 'FIELD_ID', 'YY005_FIELD_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY006_VALIDATION', 'VALIDATION_ID', 'YY006_VALIDATION_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY007_VALIDATION_RULE', 'VALIDATION_RULE_ID', 'YY007_VALIDATION_RULE_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY010_DOCUMENT', 'DOCUMENT_ID', 'YY010_DOCUMENT_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY011_DOCUMENT_DATA', 'DOCUMENT_DATA_ID', 'YY011_DOCUMENT_DATA_SEQ');
	NTC_UTIL.RESET_SEQ_TO_DATA('FAST', 'YY014_SUBMISSION', 'SUBMISSION_ID', 'YY014_SUBMISSION_SEQ');

	dbms_output.put_line('=======================================================');
END;